export default Language = {
   just_created:"Recien creado",
   accepted_by_admin:"Accepted by admin",
   accepted_by_restaurant:"Aceptado",
   assigned_to_driver:"Assigned to driver",
   prepared:"Preparado",
   picked_up:"Recogido",
   delivered:"Entregado",
   rejected_by_admin:"Rechazado",
   rejected_by_restaurant:"Rechazar",
   updated:"Actualizado",
   closed:"Terminado",
   rejected_by_driver:"Reject",
   accepted_by_driver:"Accept",
   prepared_order:"Order prepared",
   prepared_order_info:"Make this action only when order is ready.",
   VendorCreated:"Vendor is created",
   today:"Today",
   this_week:"This week",
   this_month:"This month",
   previous_month:"Previous month",
   by_doing:"by doing",
   hi:"Hi",
   borraritem:"Borrar producto",
   borraritem_sub:"¿Estás seguro de que quieres eliminar este producto del pedido?",
   today_you_have_made:"Today you have made",
   earnings:'Ganancias',
   call:"Call",
   directions:"Directions",
   close_order:"Terminar pedido",
   close_order_info:"¿Estás seguro de que quieres marcar como terminado el pedido?",
   deliver_order:"Entregar pedido",
   deliver_order_info:"¿Estás seguro de que quieres marcar como entregado el pedido?",
   pickup_order:"Pickup order",
   pickup_order_info:"Make this action only when you have picked up the order.",
   order_is_delivered:"Make this action only when you have delivered up the order.",
   order_is_paid:"Order is already payed by the client.",
   order_need_to_be_paid:"Order is not paid yet. Client needs to give you",
   order_is_prepared:"Prepared. You may head up to to venue to pick up.",
   you_will_earn:"You will earn:",
   recogerenbarra:"Recoger en barra",
   no_items:"No se encuentran pedidos nuevos.",
   order_is_delivered:"You have delivered this order.",
   order_is_in_making:"At the moment order is in preparing. No action for you at the moment. Based on desired delivery time, you may head up to the venue.",
   accept_order:"Aceptar pedido",
   accept_order_info:"¿Estás seguro de que quieres aceptarlo?.",
   reject_order:"Reject order",
   reject_order_info:"This action will reject the order",
   actions:"Acciones",
   driverWorkingStatus:"I'm available for receiving orders",
   DriverCreated:"Thanks for signing up. Driver account is created, but it requires admin approval. You will be contacted on yhe phone number you have provided",
   Restaurant: "Restaurants",
   searchRestaurants: "What are you looking for?",
   searchInRestaurant: "What are you looking for eating?",
   addToCart:"Add to cart",
   addToOrder:"Add to order",
   quatity:"Quantity",
   pay_with_paypal:"PayPal",
   pay_with_paystack:"PayStack",
   pay_with_mollie:"Mollie",
   item:"Item",
   items:"Productos",
   itemAddedInCart:"Item is added in cart",
   itemsAddedInCart:"Items are added in cart",
   order:"Pedido",
   cartSubtotal:"Cart Subtotal",
   subtotal:"Subtotal",
   proceedToCheckout:'Proceed To Checkout',
   noOrders:'There are no orders',
   orders:'Pedidos',
   noItemsInCart:'There are no items in cart',
   profile:'Perfil',
   home:"Home",
   myOrders:"My Orders",
   addresses:"Addresses",
   login:"Iniciar Sesión",
   logout:"Logout",
   forgotPassword:"Olvidé la contraseña",
   register:"Register",
   userIsNowLoggedIn:"Iniciando sesión",
   proceedToLoginFirst:"Login or register to continue",
   selectAddress:"Select Address",
   noAddressesAddNew:"No addresses found!",
   addAddress:"Add Address",
   enterYourAddress:"Enter your address",
   continue:"Continue",
   addressDetails:"Address Details",
   addressNumber:"Address Number",
   intercom:"Intercom",
   appartment:"Appartment number",
   entry:"Entry number",
   floor:"Floor",
   addressForDelivery:"Address for delivery",
   checkout:"Checkout",
   deliveryOrPickup:"Deliver / Pickup",
   deliveryTime:"Hora de entrega",
   pickupTime:"Hora de entrega",
   restaurantInformations:"Restaurant Informations",
   delivery:"Entregar en mesa",
   delivered:"Entregado",
   pickup:"Recoger",
   addNewAddress:"Add new address",
   summary:"Resumen",
   deliveryMethod:"Método de entrega",
   total:"Total",
   paymentMethod:"Payment method",
   pay_with_card:"Pay with card",
   cod:"Cash on deliver",
   cop:"Cash on pickup",
   place_order:"Place order",
   orderSuccesfull:"Order has been received succefully",
   trackOrder:"You can track and see the status of the order in the orders tab.",
   ok:"Confirmar",
   cancel:"Cancelar",
   errorOnOrder:"Error on placing the order.",
   status:"Estado",
   created:"Creado",
   orderDetails:"Detalles pedido",
   restaurant:"Restaurante",
   deliveryAddress:"Delivery address",
   orderTracking:"Order tracking",
   orderNumber:"Número de pedido",
   driver:"Delivery driver",
   driverName:"Driver name",
   driverPhone:"Driver phone",
   orderOptions:"Order options",
   all:"All",
   notifications:'Notificaciones',
   noNotifications:"No notifications",
   restaurantClosed:"Looks like restaurant is closed at this time. Order can't be made.",
   you_can_order_items_from_different_restaurants:"You can't order items from different restaurants in single order.",
   options:"Options",
   extras:"Extras",
   notInRange:"Not in range",
   selectYourCity:"Select your city"
  }
